GET https://lectortmo-api.herokuapp.com/manhwas
# Cookie: auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjcxNTE3MjQ3NmU3MTY1NTdiMmY2NDQiLCJpYXQiOjE2MDEzMTcwODJ9.bnWo0wBgdhcnf27BPizryFFQIbSN6ylYYlqfaIC8w30; Max-Age=3; Path=/; Expires=Mon, 28 Sep 2020 18:18:06 GMT; HttpOnly

###
GET http://localhost:4000/api/trending/seinen
# Cookie: auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjcxNTE3MjQ3NmU3MTY1NTdiMmY2NDQiLCJpYXQiOjE2MDEzMjMyNDZ9.NyyUODwCeIMEY1xrmVXvRZbF3FEs7exhIv8JVzlkOwc; Max-Age=3; Path=/; Expires=Mon, 28 Sep 2020 20:00:50 GMT; HttpOnly; Secure

###
GET http://localhost:4000/api/file/Sister-Neighbors
# Cookie: auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjcxNTE3MjQ3NmU3MTY1NTdiMmY2NDQiLCJpYXQiOjE2MDEzMjMyNDZ9.NyyUODwCeIMEY1xrmVXvRZbF3FEs7exhIv8JVzlkOwc; Max-Age=3; Path=/; Expires=Mon, 28 Sep 2020 20:00:50 GMT; HttpOnly; Secure


###

POST http://localhost:4000/user/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "trestres"
}

###

POST http://localhost:4000/user/register
Content-Type: application/json

{
  "username": "test",
  "email": "test@test.com",
  "password": "12345678"
}

###

POST http://localhost:4000/api/upload/5f8ce61bf386103500a5ccd7
Content-Type: application/json
Cookie: auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjhjZTYxYmYzODYxMDM1MDBhNWNjZDciLCJpYXQiOjE2MDM1MTEyMTJ9.StqnPD7lv5jtkNm-5cCwVY1jGhKiVSt0XDsDRNU8xC0; Max-Age=3; Path=/; Expires=Sat, 24 Oct 2020 03:46:56 GMT; HttpOnly

{
  "title": "Torre de Diosssss",
  "description": "Existe una torre que si uno tuviera que llegar a la cima, cualquier deseo puede ser concedido. Pero, para ser capaz de subir a la torre, sólo los elegidos pueden entrar y subir hacia la cima. Sin embargo, Baam, sólo un niño, fue capaz de entrar a la torre su único pensamiento era buscar a su querida amiga. Ignorante de su situación, un Guardián de la Torre le dio una opcion a baam. Baam lo único que entendía era que él podría obtener su respuesta en la cima de la torre. Incluso después de su exitoso paso en el primer piso, Baam todavía no se dio cuenta qué tipo de lugar al cual se habia adentrado sólo con el deseo y la ingenuidad, se embarca en un viaje hacia las mortales pruebas de cada piso.",
  "imageURL": "https://otakuteca.com/images/books/cover/8206_TMOmanga100413.jpg",
  "type": "Manhwa",
  "demography": "Shounen",
  "status": "En progreso",
  "tags": ["Accion", "Aventura", "Fantasia", "Drama", "Comedia", "Misterio"]
}


###

PATCH http://localhost:4000/manhwas/5f839b4cfa3e0224f368efc7/5f7d0fee21f7750017ff3708
Content-Type: application/json
Cookie: auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjdkMGZlZTIxZjc3NTAwMTdmZjM3MDgiLCJpYXQiOjE2MDI0NjA5MTN9.ZfZJBb6JAJmCFDF5x3-6VC61q3LTSie9n1ujJUnSEf0; Max-Age=3; Path=/; Expires=Mon, 12 Oct 2020 00:01:56 GMT; HttpOnly

{
  "title": "prueba-chapters-title"
}

###

DELETE http://localhost:4000/api/5f93b1569155d66f39b2f4a5/5f8ce61bf386103500a5ccd7
Cookie: auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjhjZTYxYmYzODYxMDM1MDBhNWNjZDciLCJpYXQiOjE2MDM1MTEyMTJ9.StqnPD7lv5jtkNm-5cCwVY1jGhKiVSt0XDsDRNU8xC0; Max-Age=3; Path=/; Expires=Sat, 24 Oct 2020 03:46:56 GMT; HttpOnly

###

PATCH  http://localhost:4000/user/lists
Content-Type: application/json

# {
#   "list": "following",
#   "userId": "5f8ce61bf386103500a5ccd7",
#   "fileId": "5f93565f9cf4e52682463dc2",
#   "prevList": null
# }

###

GET  http://localhost:4000/user/5f8ce61bf386103500a5ccd7/following
Content-Type: application/json
