GET https://lectortmo-api.herokuapp.com/manhwas
Cookie: auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjcxNTE3MjQ3NmU3MTY1NTdiMmY2NDQiLCJpYXQiOjE2MDEzMTcwODJ9.bnWo0wBgdhcnf27BPizryFFQIbSN6ylYYlqfaIC8w30; Max-Age=3; Path=/; Expires=Mon, 28 Sep 2020 18:18:06 GMT; HttpOnly

###
GET http://localhost:4000/manhwas/user/5f7d0fee21f7750017ff3708
# Cookie: auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjcxNTE3MjQ3NmU3MTY1NTdiMmY2NDQiLCJpYXQiOjE2MDEzMjMyNDZ9.NyyUODwCeIMEY1xrmVXvRZbF3FEs7exhIv8JVzlkOwc; Max-Age=3; Path=/; Expires=Mon, 28 Sep 2020 20:00:50 GMT; HttpOnly; Secure

###
GET http://localhost:4000/manhwas/Sister Neighbors
# Cookie: auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjcxNTE3MjQ3NmU3MTY1NTdiMmY2NDQiLCJpYXQiOjE2MDEzMjMyNDZ9.NyyUODwCeIMEY1xrmVXvRZbF3FEs7exhIv8JVzlkOwc; Max-Age=3; Path=/; Expires=Mon, 28 Sep 2020 20:00:50 GMT; HttpOnly; Secure
5f651c9630328119891ac0c5
###

POST http://localhost:4000/user/login
Content-Type: application/json

{
  "email": "ricqrdo@ricqrdo.com",
  "password": "trestres"
}

###

POST http://localhost:4000/user/register
Content-Type: application/json

{
  "username": "ricqrdo",
  "email": "test@test.com",
  "password": "12345678"
}

###

POST http://localhost:4000/manhwas/upload/5f7d0fee21f7750017ff3708
Content-Type: application/json
Cookie: auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjdkMGZlZTIxZjc3NTAwMTdmZjM3MDgiLCJpYXQiOjE2MDIzNzc4ODJ9.uKRj3Vb_niJt7fXB9C1wsf8fB3x14WQ_KDf79DOcEEA; Max-Age=3; Path=/; Expires=Sun, 11 Oct 2020 00:58:05 GMT; HttpOnly

{
  "title": "prueba3",
  "description": "Se ve weno",
  "imageURL": "https://otakuteca.com/images/books/cover/5e711702ab21c.jpg",
  "type": "Manhwa",
  "demography": "Seinen",
  "status": "En progreso",
  "tags": ["Ecchi", "Romance", "Comedia"]
}


###

PATCH http://localhost:4000/novels/5f825b595b151018228515b7/5f7d0fee21f7750017ff3708
Content-Type: application/json
Cookie: auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjdkMGZlZTIxZjc3NTAwMTdmZjM3MDgiLCJpYXQiOjE2MDIzNzc4ODJ9.uKRj3Vb_niJt7fXB9C1wsf8fB3x14WQ_KDf79DOcEEA; Max-Age=3; Path=/; Expires=Sun, 11 Oct 2020 00:58:05 GMT; HttpOnly

{
  "title": "prueba editada xd",
  "description": "se ve editado xd",
  "imageURL": "https://otakuteca.com/images/books/cover/5e711702ab21c.jpg",
  "type": "Manhwa",
  "demography": "Seinen",
  "status": "En progreso",
  "tags": ["Ecchi", "Romance", "Comedia"]
}

###

DELETE    http://localhost:4000/mangas/5f825aaf73678f179f3ae761/5f7d0fee21f7750017ff3708
Cookie: auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjdkMGZlZTIxZjc3NTAwMTdmZjM3MDgiLCJpYXQiOjE2MDIzNzc4ODJ9.uKRj3Vb_niJt7fXB9C1wsf8fB3x14WQ_KDf79DOcEEA; Max-Age=3; Path=/; Expires=Sun, 11 Oct 2020 00:58:05 GMT; HttpOnly